# requiring the environment of Ruby 2.3.x
image: ruby:2.3
# add bundle cache to 'vendor' for speeding up builds
cache:
  paths:
   - vendor/
before_script:
         -  gem install jekyll -v 1.5
         -  gem install jekyll-gist -v 1.5 
         -  gem install jekyll-sitemap -v 1.4
         -  gem install jekyll-seo-tag -v 1.4
# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  script:
   - jekyll _2.4_ build -d public/
  artifacts:
     paths:
       - public
  only:
   - master # this job will affect only the 'master' branch