# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            World of Puneeth
tagline:          'Learn | Laugh | Love'
description:      'Learn | Laugh | Love'
url:              http://puneeth2001.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins: [jekyll-paginate]

exclude:
         - vendor
         - Gemfile
         - Gemfile.lock
         - node_modules
         - gulpfile.js
         - package.json